Airportfinder/Models/AirInfo.cs
namespace Airportfinder.Models
{
    public class AirInfo
    {

        public string IataCode { get; set; }
        public string AirportName { get; set; }
        public string City{ get; set; }
        public double Distance { get; set; }
    }
    public class State
    {
        public string Statename { get; set; }
    }

}

Airportfinder/Models/AirportInfo.cs
using System.ComponentModel.DataAnnotations;

namespace Airportfinder.Models
{
    public class AirportInfo
    {
        [Key]
        public string IataCode { get; set; }
        [Required]
        public string AirportName { get; set; }
        public string City { get; set; }
        public string State { get; set; }
        public string Country { get; set; }
        public double Latitude { get; set; }
        public double Longitude { get; set; }

    
    }
}

Airportfinder/Models/CityInfo.cs
using Microsoft.EntityFrameworkCore;
using System.ComponentModel.DataAnnotations;

namespace Airportfinder.Models
{
    
    public class CityInfo
    {
        [Key]
        public string CityName { get; set; }
       
        public double Latitude { get; set; }
        public double Longitude { get; set; }
    }
}

Airportfinder/Models/ErrorViewModel.cs
namespace Airportfinder.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Airportfinder/Models/Location.cs
namespace Airportfinder.Models
{
    public class Location
    {
        public double Latitude { get; set; }
        public double Longitude { get; set; }
        public Location(double latitude, double longitude)
        {
            Latitude = latitude;
            Longitude = longitude;
        }
    }
}

Airportfinder/Models/StateImg.cs
using Microsoft.EntityFrameworkCore;
using System.ComponentModel.DataAnnotations;

namespace Airportfinder.Models
{
   
    public class StateImg
    {
        [Key]
        public string State { get; set; }

        public string Photo { get; set; }
    }
}

Airportfinder/Controllers/AirportController.cs
using Airportfinder.Services;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace Airportfinder.Controllers
{
    public class AirportController : Controller
    {
        private readonly IAirportInfo _airportInfoService;

        private readonly ICityInfo _cityInfoService;
        private readonly IStateImg _stateImgService;

        public AirportController(IAirportInfo airportInfoService, ICityInfo cityInfoService, IStateImg stateImgService)
        {
            _airportInfoService = airportInfoService;
            _cityInfoService = cityInfoService;
            _stateImgService = stateImgService;
        }
        
        public IActionResult Index()
        {
            return View();
        }
        public IActionResult Create()
        {
            var cityList = _cityInfoService.GetCityList().AsEnumerable();

            ViewBag.source = new SelectList(cityList, "CITY", "CITY");
            ViewBag.destination = new SelectList(cityList, "CITY", "CITY");

            return View();
        }
        [HttpPost]
        public IActionResult Create(IFormCollection form)
        {
            string From = form["source"].ToString();
            string To = form["destination"].ToString();
            if (From == To)
            {
                TempData["Error"] = "Source and destination cannot be same";
                return RedirectToAction("Create");
            }
            else
                return View("AirportDisplay", _airportInfoService.GetAirportsandDistance(From, To));
        }

        public IActionResult About()
        {
            return View();
        }

        public IActionResult Cost()
        {
            var airportList = _airportInfoService.GetAllAirports().AsEnumerable();

            ViewBag.source = new SelectList(airportList, "AirportName", "AirportName");
            ViewBag.destination = new SelectList(airportList, "AirportName", "AirportName");

            return View();
        }

        [HttpPost]
        public IActionResult Cost(IFormCollection form)
        {
            string From = form["From1"].ToString();
            string To = form["To1"].ToString();

            Tuple<string, string> costDetails = _airportInfoService.GetCostDetails(From,To);

            TempData["dist"] = $"The distance between {From} and {To} is {costDetails.Item1} Kms, Cost incurred is   ";
            TempData["Cost"] = $"INR(₹):{costDetails.Item2}";

            return View();
        }

        public IActionResult StateWiseAirports()
        {
            var state = _stateImgService.GetStateImgList();
            return View(state);
        }

        [HttpPost]
        public IActionResult StateWiseAirports(string State)
        {

            if(!string.IsNullOrEmpty(State))
            {
                var statelist = _stateImgService.GetStateImgList();
                statelist = statelist.Where(x => x.State.ToLower().Contains(State.ToLower())).ToList();
                if (statelist.Count > 0)                
                    return View(statelist);                
            }           
            return View();           
        }

        public IActionResult AirportList(string id)
        {           
            return View (_airportInfoService.GetAirportsbyId(id));
        }

        public ActionResult Services()
        {
            return View();
        }
    }
}

Airportfinder/Controllers/HomeController.cs
using Airportfinder.Models;
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;

namespace Airportfinder.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Airportfinder/Views/Airport/About.cshtml
@{
    ViewBag.Title = "About";
}



<html>
<head>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.3.1/dist/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
</head>
<body style="background-color: lightblue">
    <div class="abt">
        <h1>About Us</h1>
        <p>Whether you're looking for an airport near you, or you're planning a trip, Airport Finder can help.</p>
    </div>




    <div class="pilot">
        <section class="about">
            <div class="about-image">



                <img src="~/images/pilot.png" class="img-rounded" alt="flight">
            </div>

        </section>



    </div>
    <div class="about-content">
        <br />
        <br />
        <h2>Welcome to the Airport Finder application!</h2>
        <p>
            Welcome to the Airport Finder application! This app is designed to help you find airports around India,
            quickly and easily. Whether you're looking for an airport near you, or you're planning a trip,
            Airport Finder can help.<br />



            <b style="font-family:'Copperplate Gothic'"> Features</b><br />



            Search for airports between two cities.<br />
            Search for airports by State.<br />
            @*View airport information, including location,cost,distance.
                Get directions to airports from your current location.*@
            Save your favorite airports for quick reference.<br />



            <b style="font-family:'Copperplate Gothic'"> Benefits</b><br />



            Save time and hassle when planning your travel.<br />
            Find the perfect airport for your needs.
            @*Get directions to airports from anywhere.*@
            @*Keep track of your favorite airports.*@



        </p>



    </div>
</body>
</html>
<style>
    .abt {
        width: 90%;
        display: flex;
        justify-content: center;
        align-items: center;
        flex-direction: column;
        text-align: center;
        margin: 20px auto;
    }

        .abt h1 {
            font-size: 50px;
            color: #000;
            margin-bottom: 25px;
            position: relative;
        }

         /*   .abt h1::after {
                content: "";
                position: absolute;
                width: 100%;
                height: 4px;
                display: block;
                margin: 0 auto;
                background-color: #0094ff;
            }*/

        .abt p {
            font-family:'Gill Sans MT';
            font-size: 18px;
            color: #666;
            margin-bottom: 35px;
        }





    .pilot {
        width: 90%;
        margin: 0 auto;
        padding: 10px 20px;
    }

    .about {
        display: flex;
        justify-content: space-between;
        align-items: center;
        flex-wrap: wrap;
    }



    .about-image {
        float: left;
        margin-right: 30px;
        /* overflow:hidden;*/
    }

        .about-image img {
            max-width: 55%;
            height: 55%;
            display: block;
            transition: 0.3s ease;
        }

        .about-image:hover img {
            transform: scale(0.9);
        }

    .about-content {
        margin-right: 30px;
        float: right;
        margin-left: 650px;
        margin-top: -400PX;
    }

        .about-content h2 {
            font-family:'Copperplate Gothic';
            font-size: 23px;
            margin-bottom: 15px;
            color: darkblue;
        }

        .about-content p {
            font-family: 'Gill Sans MT';
            font-size: 18px;
            line-height: 1.5;
            color: black;
        }
</style>

Airportfinder/Views/Airport/AirportDisplay.cshtml
@model IEnumerable<Airportfinder.Models.AirInfo>




<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.4.1/dist/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">



<style>
    body {
        background-image: url('../../images/bg2.jpg');
        background-repeat: no-repeat;
        background-attachment: fixed;
        background-size: 100% 100%;
    }
</style>
<div class="container">
    <table class="table table-striped">
        <thead class="thead-blue">
            <tr>
                <th> S.No</th>
                <th>
                    @Html.DisplayNameFor(model => model.IataCode)



                </th>
                <th>
                    @Html.DisplayNameFor(model => model.AirportName)



                </th>
                <th>
                    @Html.DisplayNameFor(model => model.City)
                </th>





                <th></th>
            </tr>
        </thead>
        <tbody id="mytable">
            @foreach (var item in Model)
            {
                <tr>
                    <td>
                        @Html.DisplayFor(modelItem => item.IataCode)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.AirportName)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.City)
                    </td>
                </tr>
            }
        </tbody>
    </table>
</div>



<script>    var table = document.getElementById("mytable");
    var rows = table.getElementsByTagName("tr");



    for (var i = 0; i < rows.length; i++) {
        var row = rows[i];
        var idcell = document.createElement("td");
        idcell.textContent = i + 1;
        row.insertBefore(idcell, row.firstChild);




    }</script>

Airportfinder/Views/Airport/AirportList.cshtml
@model IEnumerable<Airportfinder.Models.AirportInfo>
@{
    ViewBag.Title = "AirportList";
}
<body class="servbg">
    <h2>AirportList</h2>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.4.1/dist/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">



    <table class="table table-striped">
        <thead>
            <tr>
                <th>S.No</th>
                <th>
                    @Html.DisplayNameFor(model => model.IataCode)
                </th>



                <th>
                    @Html.DisplayNameFor(model => model.AirportName)
                </th>



                <th>
                    @Html.DisplayNameFor(model => model.City)
                </th>



            </tr>
        </thead>
        <tbody id="mytable">



            @foreach (var item in Model)
            {
                <tr>




                    <td>
                        @Html.DisplayFor(modelItem => item.IataCode)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.AirportName)
                    </td>



                    <td>
                        @Html.DisplayFor(modelItem => item.City)
                    </td>



                </tr>
            }
        </tbody>
    </table>
    <script>
        var table = document.getElementById("mytable");
        var rows = table.getElementsByTagName("tr");

        for (var i = 0; i < rows.length; i++) {
            var row = rows[i];
            var idcell = document.createElement("td");
            idcell.textContent = i + 1;
            row.insertBefore(idcell, row.firstChild);


        }</script>
</body>

Airportfinder/Views/Airport/Index.cshtml
@{
    ViewBag.Title = "Home Page";
}

<html>
<head>
    <link href="~/css/style.css" rel="stylesheet" />
    <script src="~/js/jquery.min.js"></script>
    <script src="~/js/responsiveslides.min.js"></script>
    <a href="~/fonts/glyphicons-halflings-regular.eot"></a>
    <a href="~/fonts/glyphicons-halflings-regular.ttf"></a>
    <a href="~/fonts/glyphicons-halflings-regular.woff"></a>
    <a href="~/fonts/glyphicons-halflings-regular.woff2"></a>
</head>

<body class="indexbg">


    <div class="indexslide">
        <div class="outer">
        </div>
    </div>
    @*<div class="indexcnt">
    <h1>Welcome To Mphasis Airlines</h1>
    <p>
    “When once you have tasted flight, you will forever walk the earth with your eyes turned skyward, <br />for there you have been, and there you will always long to return.”
    <div style="margin-left:900px;font-weight:bold">
    – Leonardo DaVinci
    </div>
    </p>
    </div>*@
    <div class="header_bottom">

        <script src="js/jquery.min.js"></script>
        <script src="js/responsiveslides.min.js"></script>
        <script>
            // You can also use "$(window).load(function() {"
            $(function () {
                // Slideshow 1
                $("#slider1").responsiveSlides({
                    auto: true,
                    nav: true,
                    speed: 500,
                    namespace: "callbacks",
                });
            });</script>



    </div>


    <div class="footer">


        <p> <b>© 2023 Mphasis Airlines. All Rights Reserved.</b></p>

    </div>


</body>
</html>

Airportfinder/Views/Airport/Services.cshtml
@{
    ViewBag.Title = "Services";
}



<html>
<head>
    <link href="~/css/style.css" rel="stylesheet" />
    <script src="~/js/jquery.min.js"></script>
    <script src="~/js/responsiveslides.min.js"></script>
    <a href="~/fonts/glyphicons-halflings-regular.eot"></a>
    <a href="~/fonts/glyphicons-halflings-regular.ttf"></a>
    <a href="~/fonts/glyphicons-halflings-regular.woff"></a>
    <a href="~/fonts/glyphicons-halflings-regular.woff2"></a>
</head>
<body class="servbg">


    <h1 class="servtitle" style="font-family: 'Copperplate Gothic'; margin-top: 10px;  text-align: center; font-weight: bold; font-size: 50px; color: #000; margin-bottom: 25px; position: relative;">
        Our Services
    </h1>



    <div class="header_bottom">



        <script src="js/jquery.min.js"></script>
        <script src="js/responsiveslides.min.js"></script>
        <script>
            // You can also use "$(window).load(function() {"
            $(function () {
                // Slideshow 1
                $("#slider1").responsiveSlides({
                    auto: true,
                    nav: true,
                    speed: 500,
                    namespace: "callbacks",
                });
            });</script>



    </div>

    <style>
        .flexing {
            display: flex;
            flex-direction: row;
        }

        .lefting {
            margin-left: 5%;
        }

        .center {
            margin-left: 8%;
        }

        .righting {
            margin-left: 7%;
        }
    </style>
    <div class="flexing">
        <div class="lefting">
            <div class="card-container">
                <div class="card">
                    <img src="~/images/city.png" style="height:100px" ; width="100" alt="" />
                    <div class="card-content">
                        <h2>AIRPORT FINDER</h2>
                        <p>Want to find the airports between Two Cities?</p>
                        <div class="read_more"> <h3><a href="~/Airport/Create">EXPLORE HERE</a></h3> </div>
                    </div>
                </div>
            </div>
        </div>



        <div class="center">
            <div class="card-container">
                <div class="card">
                    <img src="~/images/state.png" style="height:100px" ; width="100" alt="" />
                    <div class="card-content">
                        <h2>STATEWISE AIRPORTS</h2>
                        <p>Want to find the airports list inside the states of India?</p>
                        <div class="read_more"> <h3><a href="~/Airport/StateWiseAirports"> EXPLORE HERE</a></h3> </div>




                    </div>
                </div>
            </div>
        </div>


        <div class="righting">
            <div class="card-container">
                <div class="card">
                    <img src="~/images/cost.png" style="height:100px" ; width="100" alt="" />
                    <div class="card-content">
                        <h2>COST CALCULATOR</h2>
                        <p>Want to find the cost of the flight ticket between two airports?</p>
                        <div class="read_more"> <h3><a href="~/airport/Cost"> EXPLORE HERE</a></h3> </div>




                    </div>
                </div>
            </div>
        </div>
    </div>


</body>
</html>

Airportfinder/Views/Airport/StateWiseAirports.cshtml
@model IEnumerable<Airportfinder.Models.StateImg>
@{
    ViewBag.Title = "StateWiseAirports";
}




<html>



<head>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-9ndCyUaIbzAi2FUVXJi0CjmCapSmO7SnpJef0486qhLnuZ2cdeRhO02iuK6FUUVM" crossorigin="anonymous">



</head>



<body style="background-color:lightblue">

    <div>
        <h2 style="text-align:center"><b>Find a State</b></h2>
        <h4 style="color:brown;text-align:center">Time To Travel In The World </h4>
    </div>
    <div style="text-align:center">@TempData["state"]</div>
    <div class="container-fluid">
        <div class="row">
            @using (Html.BeginForm("StateWiseAirports", "Airport", FormMethod.Post))
            {
                <div class="form-horizontal">
                    <div class="col-md-4">
                        <label></label>
                    </div>
                    <div class="col-md-3">
                        <div class="searchbox"> <input type="text" name="state" class="form-control" placeholder="Find state" /></div>
                    </div>
                    <div class="col-md-2">
                        <div class="margin"> <button class="btn btn-primary" type="submit">  <span class="glyphicon glyphicon-search"></span> Search</button></div>
                    </div>
                    <div class="col-md-4"></div>
                </div>
            }
        </div>
    </div>
    <style>
        .margin {
            margin-left: 155%;
            margin-top: -21%;
        }

        .searchbox {
            -moz-border-right-colors: darkblue;
        }
    </style>




    <div class="container-fluid" style="margin-top:10px;">
        @if (Model != null)
        {
            <div class="row">
                @foreach (var m in Model)



                {
                    <div class="col-md-4" style="margin-top:20px">
                        <div class="card" style="width: 20rem; border-radius: 10px">
                            <img class="card-img-top" src="~/Img/@m.Photo" alt="Card image cap" style="height:15rem;width:20rem;">
                            <div class="card-body">
                                <h5 class="card-title">@m.State</h5>
                                <span id="actlink">@Html.ActionLink("View Airports", "AirportList", new { @id = m.State })</span>
                            </div>
                        </div>
                    </div>
                }



            </div>
        }
        else
        {
            <div style="text-align:center; color:red"><h4>No Results found</h4></div>
        }



    </div>



    <script src="https://unpkg.com/ionicons@5.4.0/dist/ionicons.js"></script>



    <script src="~/Scripts/jquery.validate.unobtrusive.min.js"></script>



    <script src="~/Scripts/jquery.validate.min.js"></script>



</body>



</html>

Airportfinder/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

Airportfinder/Views/Shared/_Layout.cshtml
<html>
<head>
    <link href="~/css/style.css" rel="stylesheet" />
    <script src="~/js/jquery.min.js"></script>
    <script src="~/js/responsiveslides.min.js"></script>
    <a href="~/fonts/glyphicons-halflings-regular.eot"></a>
    <a href="~/fonts/glyphicons-halflings-regular.ttf"></a>
    <a href="~/fonts/glyphicons-halflings-regular.woff"></a>
    <a href="~/fonts/glyphicons-halflings-regular.woff2"></a>
</head>
<body>

    <div class="header">
        <div class="header_top">
            <div class="logo">
                <img src="~/images/mlogo1.png" style="height:60px ;width:46px;float:left" />
                <a href="../airportinfoes/Index">
                    <h1 style="padding: 12px 95px;margin-left:-45px"><b>MPHASIS AIRLINES</b></h1>
                    @*<h2>AIRLINES</h2>*@
                </a>
            </div>
            <div class="menu" style="font-weight:bold">
                <ul>
                    <li><a href="../Airport/Index"><em>HOME</em></a></li>
                    <li><a href="../Airport/Services"><em>SERVICES</em></a></li>
                    <li><a href="../Airport/About"><em>ABOUT US</em></a></li>
                </ul>
            </div>
            <div class="clear"></div>
        </div>
    </div>



    <div class="container body-content">
        @RenderBody()



    </div>








@*
    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")*@
    @RenderSection("scripts", required: false)



</body>
</html>